name: Executar Scraper

on:
  schedule:
    - cron: '30 12 * * *' # Executa às 09h30 BRT (12h30 UTC)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar o scraper
        run: python -m bot.scraper.py
