name: Executar Scraper

on:
  schedule:
    - cron: "00 12 * * *"
    - cron: "00 20 * * *"
    - cron: "00 03 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Definir variáveis de ambiente
        run: |
          echo "EMAIL=${{ secrets.EMAIL }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV

      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar o scraper
        run: python -u bot/scraper.py
